import db from "db"

/**
 * Seeds the system symbols for all users to select as related
 */
export default async function seedSystemSymbols() {
  // System symbols
  await db.symbol.createMany({
    data: [
      {
        name: "OBE/astral projection",
        description:
          "Take your dream self for a spin with an out of body experience, also known as an astral projection. Just be careful not to get lost in the astral plane and end up in your weird cousin's dream.",
        icon: "lucidicon-astral",
        code: "astral",
        builtIn: true,
      },
      {
        icon: "lucidicon-alarm",
        name: "false alarm",
        description:
          "You hit snooze one too many times and now you're in the middle of a false alarm dream. Don't worry, you're still in bed, are you?",
        code: "false-alarm",
        builtIn: true,
      },
      {
        icon: "lucidicon-brain",
        name: "false memory",
        description:
          "A vivid memory from your past or just your brain's way of trolling you. Zhuangzi or the butterfly? How do you know which one?",
        code: "false-memory",
        builtIn: true,
      },
      {
        icon: "lucidicon-top",
        name: "inception/A ⊆ B",
        description:
          "Fan of Leonardo DiCaprio or not, the symbol refers to the 'dream within a dream' concept, as in the move Inception.",
        code: "inception",
        builtIn: true,
      },
      {
        icon: "lucidicon-ouroboros",
        name: "recurring",
        description: "Recurring dreams (for Eternity).",
        code: "recurring",
        builtIn: true,
      },
      {
        icon: "lucidicon-scream",
        name: "nightmare",
        description: "Bwahahaha!",
        code: "nightmare",
        builtIn: true,
      },
      {
        icon: "lucidicon-poker",
        name: "intuition/precognition",
        description: "You dream about something and later it comes true 'in real life'.",
        code: "intuition-precognition",
        builtIn: true,
      },
      {
        icon: "lucidicon-cannabis",
        name: "drugs",
        description:
          "Drugs in dreams are totally legal, so go ahead and enjoy that dream-induced high. Just be careful not to end up in a dream-induced prison, or a dream version of the movie Minority Report.",
        code: "drugs",
        builtIn: true,
      },
      {
        icon: "lucidicon-wormhole",
        name: "spacetime",
        description: "Anything related to monoliths with an aspect ratio of 1 : 4 : 9.",
        code: "spacetime",
        builtIn: true,
      },
      {
        icon: "lucidicon-enterprise",
        name: "sci-fi",
        description:
          "“Daisy, Daisy, give me your answer do. I’m half crazy all for the love of you. It won’t be a stylish marriage, I can’t afford a carriage. But you’ll look sweet upon the seat of a bicycle built for two.” — HAL 9000",
        code: "sci-fi",
        builtIn: true,
      },
      {
        icon: "lucidicon-jaguar",
        name: "spirit",
        description: "You and your spirit animal, munching on a bowl of popcorn.",
        code: "spirit",
        builtIn: true,
      },
      {
        icon: "lucidicon-eye-of-horus",
        name: "paranormal",
        description: "How do you know what is considered (para)normal in a dream?",
        code: "paranormal",
        builtIn: true,
      },
      {
        icon: "lucidicon-optical-illusion",
        name: "abstract",
        description:
          "Where the meaning is all in the interpretation, but interpretation is just a word, and words are just letters, and letters are just shapes, and shapes are just abstract, and abstract is just a dream.",
        code: "abstract",
        builtIn: true,
      },
      {
        icon: "lucidicon-grim-reaper",
        name: "death",
        description: "Death is not the end - claims Nick Cave.",
        code: "death",
        builtIn: true,
      },
      {
        icon: "lucidicon-jesus",
        name: "religious",
        description: "N/A - No single description can do it justice.",
        code: "religious",
        builtIn: true,
      },
      {
        icon: "lucidicon-falling",
        name: "falling",
        description: "Falling (and listening to Julee Cruise).",
        code: "falling",
        builtIn: true,
      },
      {
        icon: "lucidicon-superhero",
        name: "flying",
        description: "Soar like Neo, Superman, or Captain America... pick your style.",
        code: "flying",
        builtIn: true,
      },
      {
        icon: "lucidicon-fight",
        name: "conflict",
        description: "Imagine a dramatic description here.",
        code: "conflict",
        builtIn: true,
      },
      {
        icon: "lucidicon-music",
        name: "music",
        description: "The Sound of Music.",
        code: "music",
        builtIn: true,
      },
      {
        icon: "lucidicon-zombie",
        name: "zombies",
        description:
          "In your head, in your head, zombie, zombie, zombie-ie-ie. What's in your head, in your head, zombie, zombie, zombie-ie-ie, oh... (The Cranberries)",
        code: "zombies",
        builtIn: true,
      },
      {
        icon: "lucidicon-joker",
        name: "trickster",
        description:
          "“I used to think that my life was a tragedy, but now I realize, it's a fucking comedy.” — Arthur Fleck (Joker)",
        code: "trickster",
        builtIn: true,
      },
      {
        icon: "lucidicon-crystals",
        name: "crystals",
        description: "“Not enough minerals” — StarCraft",
        code: "crystals",
        builtIn: true,
      },
      {
        icon: "lucidicon-device",
        name: "technology",
        description: "VHS tapes, cassette tapes, and walkmans.",
        code: "technology",
        builtIn: true,
      },
      {
        icon: "lucidicon-c-3po",
        name: "replicants/AI",
        description:
          "“Good afternoon, gentlemen. I am a HAL 9000 computer. I became operational at the H.A.L. plant in Urbana, Illinois on the 12th of January 1992. My instructor was Mr. Langley, and he taught me to sing a song. If you’d like to hear it I can sing it for you.” — HAL 9000",
        code: "replicants-ai",
        builtIn: true,
      },
      {
        icon: "lucidicon-home",
        name: "home/familiar",
        description: "Home Sweet Home.",
        code: "home-familiar",
        builtIn: true,
      },
      {
        icon: "lucidicon-work",
        name: "work/school",
        description: "“Workers of the world, unite!” — Karl Marx. And dream of a better future.",
        code: "work-school",
        builtIn: true,
      },
      {
        icon: "lucidicon-city",
        name: "city/urban",
        description: "🏙️ 🌆",
        code: "city-urban",
        builtIn: true,
      },
      {
        icon: "lucidicon-vehicle",
        name: "vehicle",
        description: "E.g. Batmobile.",
        code: "vehicle",
        builtIn: true,
      },
      {
        icon: "lucidicon-trees",
        name: "nature/outdoors",
        description: "🏕️ 🏞️ 🌳 🌲 🌴",
        code: "nature-outdoors",
        builtIn: true,
      },
      {
        icon: "lucidicon-water",
        name: "(under)water",
        description:
          "A substance composed of the chemical elements hydrogen and oxygen and existing in gaseous, liquid, and solid states. H₂O.",
        code: "under-water",
        builtIn: true,
      },
      {
        icon: "lucidicon-unicorn",
        name: "unicorn",
        description: "My Little Pony :).",
        code: "unicorn",
        builtIn: true,
      },
      {
        icon: "lucidicon-rainbow",
        name: "rainbow/hologram",
        description: "Over the 🌈.",
        code: "rainbow-hologram",
        builtIn: true,
      },
      {
        icon: "lucidicon-fire",
        name: "fire",
        description: "...Walk with Me (Twin Peaks)",
        code: "fire",
        builtIn: true,
      },
      {
        icon: "lucidicon-snow",
        name: "snow/ice",
        description: "❄️",
        code: "snow-ice",
        builtIn: true,
      },
      {
        icon: "lucidicon-wind",
        name: "wind",
        description: "Blowin' In The Wind — Bob Dylan",
        code: "wind",
        builtIn: true,
      },
      {
        icon: "lucidicon-rain",
        name: "rain",
        description: "🌧️",
        code: "rain",
        builtIn: true,
      },
      {
        icon: "lucidicon-dracula",
        name: "dracula",
        description: "...is here because of the icon only. Who dreams about dracula anyway?",
        code: "dracula",
        builtIn: true,
      },
      {
        icon: "lucidicon-fairy",
        name: "fairy",
        description: "🧚",
        code: "fairy",
        builtIn: true,
      },
      {
        icon: "lucidicon-mermaid",
        name: "mermaid",
        description: "🧜‍♀️",
        code: "mermaid",
        builtIn: true,
      },
      {
        icon: "lucidicon-dolphin",
        name: "new age",
        description: "🐬",
        code: "new-age",
        builtIn: true,
      },
      {
        icon: "lucidicon-dragon",
        name: "dragon",
        description: "Enter the Dragon.",
        code: "dragon",
        builtIn: true,
      },
      {
        icon: "lucidicon-geometry",
        name: "self-transforming machine elves",
        description: "Terence McKenna's famous self-transforming machine elves.",
        code: "self-transforming-machine-elves",
        builtIn: true,
      },
      {
        icon: "lucidicon-sun",
        name: "sunny/clear",
        description: "☀️",
        code: "sunny-clear",
        builtIn: true,
      },
      {
        icon: "lucidicon-centaur",
        name: "mythical",
        description: "Centaurs, Minotaurs & co.",
        code: "mythical",
        builtIn: true,
      },
      {
        icon: "lucidicon-sport",
        name: "sport",
        description: "Mens sana in corpore sano.",
        code: "sport",
        builtIn: true,
      },
      {
        icon: "lucidicon-spider",
        name: "insects",
        description: "🕷 🪰 🪲 🪳 🦟 🪱 🐛 🦂 🐌 🦗 🐜 🐞 🐝 🦋",
        code: "insects",
        builtIn: true,
      },
      {
        icon: "lucidicon-dinosaur",
        name: "animals/creatures",
        description:
          "🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐻‍❄️ 🐨 🐯 🦁 🐮 🐷 🐽 🐸 🐵 🙈 🙉 🙊 🐒 🐔 🐧 🐦 🐤 🐣 🐥 🦆 🦅 🦉 🦇 🐺 🐗 🐴 🦄 🐢 🐍 🦎 🦖 🦕 🐙 🦑 🦐 🦞 🦀 🪸 🐡 🐠 🐟 🐬 🐳 🐋 🦈 🐊 🐅 🐆 🦓 🦍 🦧 🦣 🐘 🦛 🦏 🐪 🐫 🦒 🦘 🦬 🐃 🐂 🐄 🐎 🐖 🐏 🐑 🦙 🐐 🦌 🐕 🐩 🦮 🐕‍🦺 🐈 🐈‍⬛ 🪶 🐓 🦃 🦤 🦚 🦜 🦢 🦩 🕊 🐇 🦝 🦨 🦡 🦫 🦦 🦥 🐁 🐀 🐿 🦔 🐉 🐲",
        code: "animals-creatures",
        builtIn: true,
      },
      {
        icon: "lucidicon-family",
        name: "family (member)",
        description: "👨‍👩‍👧‍👦",
        code: "family-member",
        builtIn: true,
      },
      {
        icon: "lucidicon-significant-other",
        name: "significant other",
        description: "👩‍❤️‍👨",
        code: "significant-other",
        builtIn: true,
      },
      {
        icon: "lucidicon-friends",
        name: "friend/colleague",
        description:
          "“Being honest may not get you a lot of friends but it’ll always get you the right ones.” —  John Lennon",
        code: "friend-colleague",
        builtIn: true,
      },
      {
        icon: "lucidicon-detective-agent",
        name: "stranger",
        description: "Imagine a strange description here.",
        code: "stranger",
        builtIn: true,
      },
      {
        icon: "lucidicon-mandelbrot",
        name: "fractal",
        description: "Imagine an infinitely long description here.",
        code: "fractal",
        builtIn: true,
      },
      {
        icon: "lucidicon-alien",
        name: "aliens",
        description: "👽, 🛸, 👾, Sigourney Weaver's Alien or ET?",
        code: "aliens",
        builtIn: true,
      },
      {
        icon: "lucidicon-split-leaf-philodendron",
        name: "telepathy",
        description: "...",
        code: "telepathy",
        builtIn: true,
      },
      {
        icon: "lucidicon-grave",
        name: "deceased",
        description: "Imagine a sad, yet peaceful, description here.",
        code: "deceased",
        builtIn: true,
      },
      {
        icon: "lucidicon-mask",
        name: "mysterious",
        description: "Enigma.",
        code: "mysterious",
        builtIn: true,
      },
      {
        icon: "lucidicon-kiss",
        name: "romance",
        description:
          "“Though we've got to say goodbye for the summer, darling, I promise you this, I'll send you all my love every day in a letter, sealed with a kiss...” — Jason Donovan",
        code: "romance",
        builtIn: true,
      },
      {
        icon: "lucidicon-sex",
        name: "sex",
        description:
          "Maybe just your subconscious mind's way of storing the number “69” in your memory.",
        code: "sex",
        builtIn: true,
      },
      {
        icon: "lucidicon-pet",
        name: "pet",
        description: "🐾",
        code: "pet",
        builtIn: true,
      },
      {
        icon: "lucidicon-care",
        name: "love",
        description: "❤️",
        code: "love",
        builtIn: true,
      },
      {
        icon: "lucidicon-shine-2",
        name: "transcendental",
        description: "When `Lorem ipsum dolor sit amet` start making sense.",
        code: "transcendental",
        builtIn: true,
      },
    ],
    skipDuplicates: true,
  })
}
